const UNAUTHENTICATED = 'UNAUTHENTICATED';
const USER_LOGGED_IN = 'USER_LOGGED_IN';
const USER_INVALID = 'USER_INVALID';
const TOKEN_INVALID = 'TOKEN_INVALID';
const EMAIL_EXIST = 'EMAIL_EXIST';
const UNAUTHORIZED = 'UNAUTHORIZED';

module.exports = {
  UNAUTHENTICATED,
  USER_LOGGED_IN,
  USER_INVALID,
  TOKEN_INVALID,
  EMAIL_EXIST,
  UNAUTHORIZED,
};
